name: Azure Deployment

on:
    push:
      branches:
        - main
      paths:
        - 'test/*'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1.5.7

    - name: Configure Azure CLI
      run: |
        az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET
        

    - name: Initialize Terraform
      run: terraform init

    - name: Deploy Infrastructure
      run: terraform apply -auto-approve
